components/FreelancerHub.tsx
pages/bounty.tsx
pages/freelancerHub.tsx
pages/quests.tsx
pages/stats.tsx
pages/teams.tsx

Resolves: #28 
Feature: Add skeleton freelancer hub with links to other pages. Also create pages and components that the hub is linked to.

Feature: Add skeleton hub page and pages linked to it.

---

components/AddQuest.tsx
components/Quest.tsx
components/Quests.tsx
components/TagSelect.tsx
package.json
pages/addQuest.tsx
pages/index.tsx
pages/quest.tsx
pages/quests.tsx

Resolves: #26 #34 #38
Feature: Add individual quest page and component as well as a form for adding quests (no backend yet)

Feature: Add individual quest page and a basic form for adding quests

---

components/Header.tsx
pages/_app.tsx
pages/_document.tsx
pages/index.tsx
pages/login.tsx
theme/index.js
theme/index.ts

Style: add light and dark color themes

Style: add light and dark color themes

---

CONTRIBUTING.md

Create CONTRIBUTING.md file with initial best practices of writing code.

Chore: Start on CONTRIBUTING.md guidelines

---

components/LatestTeamsSlider/index.tsx
components/ScrollButtons/ScrollLeft.tsx
components/ScrollButtons/ScrollRight.tsx

Refactor: Refactor latest teams and quests slider components and the logic of buttons responsible for scrolling

Refactor: Refactor slider components

---

components/FeaturedCompanies/FeaturedCompany.tsx
components/FeaturedCompanies/index.tsx
public/GuildsLogo2.svg

Resolves: #58 
Feature: Add featured companies and featured company component with placeholder logos. Also add mobile scaling for both components.
Regular version:
Mobile large version:
Mobile small version:

Feature: Featured companies

---

components/QuestSearch/index.tsx
components/SearchComponents/RefinementList.tsx
components/TeamSearch/FindTeamBanner.tsx
components/TeamSearch/TeamHit.tsx
components/TeamSearch/TeamHits.tsx
components/TeamSearch/index.tsx
typesense/insantsearch.ts

Feature: Add teams search component, find team banner, and team hits components

Feature: Teams search

---

components/AboutTheTeamLeader/TeamLeaderAvatar.tsx
components/AboutTheTeamLeader/TeamLeaderInfo.tsx
components/AboutTheTeamLeader/index.tsx
components/HeroAvatar/index.tsx
storage/hero/types.ts

Resolves: #83 
Feature: Add about the team leader component
Fullscreen version:
Mobile version:
___________________________________________________________________________________________________________

Feature: About the team leader

---

components/AboutTheTeamLeader/index.tsx
components/FeaturedHeroesSlider/FeaturedHeroesButtons.tsx
components/FeaturedHeroesSlider/index.tsx
components/HeroAvatar/index.tsx
components/ScrollButtons/ScrollRight.tsx
storage/hero/populate.ts
storage/hero/types.ts

Resolves: #96 
Feature: Add featured heroes slider, adjust populate function, add missing types to hero interface
Fullscreen version:
Mobile version:
___________________________________________________________________________________________________________

Feature: Featured heroes slider

---

components/smallDatePicker/SmallDatePicker.tsx
components/smallDatePicker/index.tsx
package.json

Feature: Small date picker

---

components/GreenButton/index.tsx
components/LatestQuestsSlider/index.tsx
components/LatestTeamsSlider/index.tsx
components/ReusableComponents/buttons.tsx
components/UnderMaintenance/UnderMaintenance.tsx
components/WhiteButton/index.tsx

Resolves: #138 
Feature: add reusable buttons and swap every button previously created

Feature: Reusable buttons

---

components/BusinessHeroes/BuisnessHeroesSlides.tsx
components/BusinessHeroes/BusinessHeroesSlides.tsx
components/BusinessHeroes/index.tsx
components/ScrollButtons/ScrollRight.tsx

Resolves: #129 
Here is slider in action:
https://youtu.be/eLuLoT6jyoc

Feature: Fingertips slides

---

components/BountiesBalanceCard/index.tsx

Resolves: #107 
Feature: Add bounties balance card component

Feature: Add balance card component

---

components/CountrySelectDropdown.tsx
next.config.js
pages/tax-info.tsx

Resolves #160  - Add tax info pages and new country select dropdown component.
Submitting as a new PR due to conflict with lock file in previously approved PR (https://github.com/asoltd/guilds/pull/164)

Feature: tax info page

---

components/NewBid.tsx
pages/index.tsx

Resolves #162 - adds the new bid card. Mostly front end because some related components are not completed, therefore a separate task will be to connect these together and with backend.

Feature: add 'new bid' card

---

components/FilterSearchBar.tsx
typesense/instantsearch.ts

Add a reusable filter and search bar for courses, mentors etc.

reusable filter/search bar

---

components/BackToSearch/index.tsx
components/BecomeMentor.tsx
components/BidConfirm.tsx
components/Bids.tsx
components/CurrentBids.tsx
components/NewBid.tsx
components/UserCardBid.tsx
components/UserProfileCards.tsx

Resolves #174 by adding 'current bids' components:
- displays all current bids using the new user bid cards (which have been refactored into a separate component)
- finds and displays highest and lowest bid
- mobile friendly
Screenshot:

Feature: add current bids component

---

components/AboutGig/AboutGig.tsx
components/BackToSearch/index.tsx
components/CurrentBids.tsx
components/HeroAvatar/index.tsx
components/IndividualQuestBanner.tsx
components/LevelBar.tsx
pages/quest/[qid].tsx
types/hero.ts
types/quest.ts

Resolves #139 - built the individual quest page, bringing together components built previously (some refactoring and minor changes required to these).
New quest file to work with dynamic routing, so the relevant quest and hero data is loaded. 
pages/quest/[qid].tsx   ----------->  http://localhost:3000/quest/3JTOJHO9EZKgT5JIcDRX 
Front end:
Some further minor changes and fixes will be required, but works well.

Feature: assemble quest page

---

components/AboutTeam.tsx
components/IndividualTeamBanner.tsx
components/Slider/index.tsx
components/TeamHits/TeamHit.tsx
pages/team/[tid].tsx
types/team.ts

Resolves #149 - assemble individual team page:

Feature: assemble individual team page

---

pages/quests.tsx
public/search-white.svg
theme/index.ts

Added quests page. The design for this hasn't been finalised yet, so there will be additions to this.

Feature: add quests page
